### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/pre-trained_model/config.json'

### ISSUE THREAD

**Issue by meyko18** [ShawX825/HiDialog#1]
![image](https://github.com/ShawX825/HiDialog/assets/67364361/616b40aa-cad2-4cc6-9a08-e2b4bc40d583)

**Comment by ShawX825** [comment]
Hi, please also copy config file from here https://huggingface.co/roberta-large/blob/main/config.json under pre-trained_mode/RoBERTa directory. Thanks for reminding, I have updated the README.md file.
