### ISSUE TITLE
Could this project supper dataset IEMOCAP?

### ISSUE THREAD

**Issue by jacklin1218** [ShawX825/HiDialog#2]
IEMOCAP is a popular dataset in ERC task
Could this project supper IEMOCAP?

Thanks of your nice project!

**Comment by ShawX825** [comment]
Hi, ideally, HiDialog could be adapted to datasets where the input is multi-turn dialogue. You might need to customize your data processor similar to [MELD.py](https://github.com/ShawX825/HiDialog/blob/main/datasets/MELD/MELD.py).
